spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/booking_db
    username: booking_user
    password: booking_password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

server:
  port: 8081





  